variables:
  GIT_STRATEGY: clone

stages:
- build
- deploy

build:
  script:
    - echo Deploying API
  stage: build
  tags:
    - python3
    - aglio
  artifacts:
    paths:
    - sde/
    - etf-api.apib
    - server.py
    - requirements.txt
    when: on_success
    expire_in: 1 day
  allow_failure: false

deploy:
  script:
  - git checkout $CI_BUILD_REF_NAME
  - 'which distelli || (wget -qO- https://www.distelli.com/download/client | sh)'
  - "echo \"DistelliAccessToken: '$DISTELLI_ACCESS_TOKEN'\" > /etc/distelli.yml"
  - "echo \"DistelliSecretKey: '$DISTELLI_SECRET_KEY'\" >> /etc/distelli.yml"
  - echo "Environments:" >> /etc/distelli.yml
  - echo "  - EVE-Exchange-API-Production" >> /etc/distelli.yml
  - '"/usr/local/bin/distelli" login -conf /etc/distelli.yml'
  - '"/usr/local/bin/distelli" deploy -q -y -m "Deployment from Gitlab" --env EVE-Exchange-API-Production'
  stage: deploy
  environment: production
  only:
    - master
  tags:
    - python3
    - aglio
  allow_failure: false
